name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.17.x']
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up the prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu qemu-user

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        ./test_qemu.sh -test.v fmt
        ./test_qemu.sh -test.v math
        ./test_qemu.sh -test.v math/big
        ./test_qemu.sh -test.v math/bits
        ./test_qemu.sh -test.v math/cmplx
        ./test_qemu.sh -test.v math/rand
        ./test_qemu.sh -test.v -test.short runtime
        ./test_qemu.sh -test.v runtime/debug
        ./test_qemu.sh -test.v runtime/internal/atomic
        ./test_qemu.sh -test.v runtime/internal/math
        ./test_qemu.sh -test.v runtime/internal/sys
        ./test_qemu.sh -test.v strconv
        ./test_qemu.sh -test.v strings
        ./test_qemu.sh -test.v sort
        ./test_qemu.sh -test.v sync
        ./test_qemu.sh -test.v sync/atomic
        ./test_qemu.sh -test.v time
