name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.17.x']
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up the prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu qemu-user

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        ./test_qemu.sh fmt
        ./test_qemu.sh math
        ./test_qemu.sh math/big
        ./test_qemu.sh math/bits
        ./test_qemu.sh math/cmplx
        ./test_qemu.sh math/rand
        ./test_qemu.sh runtime -test.short
        ./test_qemu.sh runtime/debug
        ./test_qemu.sh runtime/internal/atomic
        ./test_qemu.sh runtime/internal/math
        ./test_qemu.sh runtime/internal/sys
        ./test_qemu.sh strconv
        ./test_qemu.sh strings
        ./test_qemu.sh sort
        ./test_qemu.sh sync
