name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.17.x', '1.18.x']
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up the prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu qemu-user

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        go run test.go -qemu -args="-test.run=^Test -test.v fmt"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/abi"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/cpu"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/fmtsort"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/itoa"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/reflectlite"
        go run test.go -qemu -args="-test.run=^Test -test.v internal/unsafeheader"
        go run test.go -qemu -args="-test.run=^Test -test.v math"
        go run test.go -qemu -args="-test.run=^Test -test.v math/big"
        go run test.go -qemu -args="-test.run=^Test -test.v math/bits"
        go run test.go -qemu -args="-test.run=^Test -test.v math/cmplx"
        go run test.go -qemu -args="-test.run=^Test -test.v math/rand"
        go run test.go -qemu -args="-test.run=^Test -test.v -test.short runtime"
        go run test.go -qemu -args="-test.run=^Test -test.v runtime/debug"
        go run test.go -qemu -args="-test.run=^Test -test.v runtime/internal/atomic"
        go run test.go -qemu -args="-test.run=^Test -test.v runtime/internal/math"
        go run test.go -qemu -args="-test.run=^Test -test.v runtime/internal/sys"
        go run test.go -qemu -args="-test.run=^Test -test.v strconv"
        go run test.go -qemu -args="-test.run=^Test -test.v strings"
        go run test.go -qemu -args="-test.run=^Test -test.v sort"
        go run test.go -qemu -args="-test.run=^Test -test.v sync"
        go run test.go -qemu -args="-test.run=^Test -test.v sync/atomic"
        go run test.go -qemu -args="-test.run=^Test -test.v time"
